DROP TABLE IF EXISTS "TRANSACTION";

CREATE TABLE "TRANSACTION" (
    "TRANSACTION_ID" uuid DEFAULT random_uuid(),
    "DESCRIPTION" VARCHAR(50) NOT NULL,
    "TRANSACTION_DATE" DATE NOT NULL,
    "AMOUNT" NUMERIC NOT NULL,
    PRIMARY KEY ("TRANSACTION_ID")
)